Lab Final Question: 

Task 2
You are given a customer churn dataset (customer_churn.csv).
1. Preprocess:
   * Encode contract_type
    * Normalize features
2. Train:
    * KNN (k=3, k=5)
    * Decision Tree (default + max_depth=3)
3. Evaluate:
   * Accuracy
    * Confusion Matrix
4. Compare models and justify which performs better

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
df = pd.read_csv("/content/churn_data.csv")
print(df.head(25))

    age  monthly_spend  tenure contract_type  support_calls churn
0    22            200       3       Monthly              5   Yes
1    35            500      12        Yearly              1    No
2    45            700      24        Yearly              0    No
3    23            150       2       Monthly              6   Yes
4    52            900      36        Yearly              0    No
5    40            650      18       Monthly              2    No
6    29            300       6       Monthly              4   Yes
7    48            800      30        Yearly              1    No
8    33            400      10       Monthly              3   Yes
9    55            950      40        Yearly              0    No
10   26            250       5       Monthly              5   Yes
11   38            600      20        Yearly              1    No
12   31            350       8       Monthly              4   Yes
13   60           1000      45        Yearly              0    No
14   28   

In [ ]:
le = LabelEncoder()
df['contract_type'] = le.fit_transform(df['contract_type'])

In [ ]:
X = df.drop("churn", axis=1)
y = df["churn"]

In [ ]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.35, random_state=42
)

KNN = 3

In [ ]:
knn3 = KNeighborsClassifier(n_neighbors=3)
knn3.fit(X_train, y_train)
pred_knn3 = knn3.predict(X_test)


KNN =5

In [ ]:
knn5 = KNeighborsClassifier(n_neighbors=5)
knn5.fit(X_train, y_train)
pred_knn5 = knn5.predict(X_test)

Default Decision Tree

In [ ]:
dt_default = DecisionTreeClassifier(random_state=42)
dt_default.fit(X_train, y_train)
pred_dt_default = dt_default.predict(X_test)

Decision Tree Depth= 3

In [ ]:
dt_limited = DecisionTreeClassifier(max_depth=3, random_state=42)
dt_limited.fit(X_train, y_train)
pred_dt_limited = dt_limited.predict(X_test)

In [ ]:
def evaluate_model(name, y_true, y_pred):
    print(f"\n===== {name} =====")
    print("Accuracy:", accuracy_score(y_true, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_true, y_pred))
    print("\nClassification Report:\n", classification_report(y_true, y_pred))

In [ ]:
evaluate_model("KNN (k=3)", y_test, pred_knn3)
evaluate_model("KNN (k=5)", y_test, pred_knn5)

evaluate_model("Decision Tree (Default)", y_test, pred_dt_default)
evaluate_model("Decision Tree (max_depth=3)", y_test, pred_dt_limited)


===== KNN (k=3) =====
Accuracy: 0.8571428571428571
Confusion Matrix:
 [[3 1]
 [0 3]]

Classification Report:
               precision    recall  f1-score   support

          No       1.00      0.75      0.86         4
         Yes       0.75      1.00      0.86         3

    accuracy                           0.86         7
   macro avg       0.88      0.88      0.86         7
weighted avg       0.89      0.86      0.86         7


===== KNN (k=5) =====
Accuracy: 0.8571428571428571
Confusion Matrix:
 [[3 1]
 [0 3]]

Classification Report:
               precision    recall  f1-score   support

          No       1.00      0.75      0.86         4
         Yes       0.75      1.00      0.86         3

    accuracy                           0.86         7
   macro avg       0.88      0.88      0.86         7
weighted avg       0.89      0.86      0.86         7


===== Decision Tree (Default) =====
Accuracy: 1.0
Confusion Matrix:
 [[4 0]
 [0 3]]

Classification Report:
               

In [ ]:
results = {
    "KNN (k=3)": accuracy_score(y_test, pred_knn3),
    "KNN (k=5)": accuracy_score(y_test, pred_knn5),
    "Decision Tree (Default)": accuracy_score(y_test, pred_dt_default),
    "Decision Tree (max_depth=3)": accuracy_score(y_test, pred_dt_limited)
}

best_model = max(results, key=results.get)

print("\n📊 Model Accuracy Comparison:")
for model, acc in results.items():
    print(f"{model}: {acc:.4f}")

print("\n🏆 Best Performing Model:", best_model)


📊 Model Accuracy Comparison:
KNN (k=3): 0.8571
KNN (k=5): 0.8571
Decision Tree (Default): 1.0000
Decision Tree (max_depth=3): 1.0000

🏆 Best Performing Model: Decision Tree (Default)
